name: Release macOS (arm64)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build macOS binary
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build distributable
        run: npm run dist:mac

      - name: Upload distributable artifact
        uses: actions/upload-artifact@v4
        with:
          name: acacia-mac-arm64
          path: release/*.dmg
          if-no-files-found: error

  release:
    name: Publish GitHub release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: acacia-mac-arm64
          path: dist

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.dmg
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
